HTML-prototype
akimov228aleksei/Django_project pull request #2
Opened 2021-01-18 18:52 UTC by akimov228aleksei

Add HTML-prototype

2021-01-19 11:04 UTC, jimmyhollywood requested changes
I think it would be nice to add pages for "add" and "delete" actions. Just to show how the features will work.

2021-01-19 11:32 UTC, akimov228aleksei commented
Removed the HTML prefix from the file names, made the "pictures" folder in lowercase.Fixed paths of pictures

2021-01-21 14:49 UTC, jimmyhollywood requested changes
Looks good, just one suggestions. When add or edit record set new name like a "Edited/Added Department/Person/Vacation"

2021-01-21 14:49 UTC, jimmyhollywood commented on Documentations/HTML_prototype/departments_after_edit.html
> +        <td style="border-bottom-color:red; border-bottom-width:2;"> 3213 $</td>
Just wondering, why the average salary is changed after editing of the department name?

2021-01-21 19:50 UTC, akimov228aleksei commented
Created missing templates. Added actions for buttons "edit" and "delete".

2021-01-23 10:37 UTC, akimov228aleksei commented on Documentations/HTML_prototype/departments_after_edit.html
> +        <td style="border-bottom-color:red; border-bottom-width:2;"> 3213 $</td>
Fixed.

2021-01-23 10:37 UTC, akimov228aleksei commented
> Выглядит хорошо, только одно предложение. При добавлении или редактировании записи установите новое имя, например «Отредактировано / Добавлен отдел / Человек / Отпуск».

Fixed.

2021-01-29 08:47 UTC, jimmyhollywood approved these changes
That is ok.
_Note: When you will work with html pages for your web application - try to use separate css files_

2021-02-01 13:39 UTC, merged