Django skeleton created and basic functionality added
akimov228aleksei/Django_project pull request #3
Opened 2021-03-15 20:00 UTC by akimov228aleksei

Django skeleton created and basic functionality added

2021-03-15 20:26 UTC, jimmyhollywood commented
First of all, add me to reviewers
The second point is that the description of the PR does not cover the changes you have added
And the last one is that some of checks of this PR are failed

2021-03-17 06:27 UTC, jimmyhollywood requested changes

2021-03-17 06:27 UTC, jimmyhollywood commented on web-app/management/department/models/department.py
> +        from department.models import Employee
I think there is possible to avoid this import here. Lets check the documentation on "Model" section

2021-03-18 21:38 UTC, akimov228aleksei commented on .github/workflows/my.yml
> +  one_build:
Fixed

2021-03-19 21:12 UTC, akimov228aleksei commented on web-app/management/department/static/department/css/department.css
> +body {
Names changed

2021-03-19 21:13 UTC, akimov228aleksei commented on web-app/management/department/templates/department/department.html
> +{% extends 'department/layout.html' %}
All indentation fixed

2021-03-19 21:13 UTC, akimov228aleksei commented on web-app/management/department/templates/department/department_add.html
> +{% load static %}
All indentation fixed

2021-03-19 21:13 UTC, akimov228aleksei commented on web-app/management/department/templates/department/department_delete.html
> +{% extends 'department/layout_delete.html' %}
All indentation fixed

2021-03-19 22:05 UTC, akimov228aleksei commented on web-app/requirements.txt
> +DateTime==4.3
This library was used to get times and output them to a template. But just now I decided to replace this with a js script.

2021-03-19 22:08 UTC, akimov228aleksei commented on web-app/management/department/views/__init__.py
> +from .department import *
Yes, as it is used in urls files. But I changed it a bit and only called the functions I needed.

2021-03-20 20:23 UTC, akimov228aleksei commented on web-app/management/department/views/department.py
> +"""Module containing application logic"""
Done

2021-03-20 23:16 UTC, akimov228aleksei commented on web-app/requirements.txt
> +
Fixed

2021-04-04 14:16 UTC, merged